In [12]:
import numpy as np
l1=[1, 2, 3, 4, 5]
arr=np.array(l1)
print(type(l1))
print(l1)
print(type(arr))
print(arr)

<class 'list'>
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [6]:
arr1 = np.arange(1, 10, )
print(arr1.size)
print(len(arr1))

print(arr1)
print(arr1.shape)



9
9
[1 2 3 4 5 6 7 8 9]
(9,)


In [15]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr2)

arr2.shape=(3,3)
print(arr2)

arr2.reshape(1, 9)
print(arr2)

print(arr2.max())

print(arr2.min())

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1


In [ ]:
zero_arr=np.zeros((3,3))
print(zero_arr)

one_arr=np.ones((3,3))
print(one_arr)

eye_arr=np.eye(3)
print(eye_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
rnd_arr=np.random.rand(3)
print(rnd_arr)

[0.32528229 0.48448142 0.22098948]


In [16]:
#CONCATENATION
np.concatenate([arr2, zero_arr], axis=0)


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr2=np.ones((3,5), dtype=bool) 
print(arr2)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [11]:
import numpy as np

# corrected reshape example with 9 elements
arr2 = np.array([1,2,3,4,5,6,7,8,9])
arr3 = arr2.reshape(3,3)
print("3x3 matrix:\n", arr3)

# demonstration of a 4x3x2 array (requires 24 elements)
arr24 = np.arange(24).reshape(4,3,2)
print("4x3x2 array shape:", arr24.shape)


3x3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
4x3x2 array shape: (4, 3, 2)


In [13]:
#1D array convert 2D array
arr2 =np.array ([1,2,3,4,5,6,7,8,9])
arr3 =arr2.reshape(4,3)

ValueError: cannot reshape array of size 9 into shape (4,3)